### ISSUE TITLE
체크리스트 조회 - id 관련

### ISSUE THREAD

**Issue by hi-subin** [KHUGREEN/greenReview_backend#13]
![image](https://user-images.githubusercontent.com/72721839/188652851-5430e616-2182-4c0f-b717-7560daff8608.png)
id를 1,2,3,4로 안하신 이유가 따로 있나요 ?

**Comment by 2480258** [comment]
그린워싱 유형 7가지 순서에서 이전에 말씀하신 걸 지워보니까 2, 3, 5, 7로 남았습니다. 혹시 1, 2, 3, 4로 필요하신가요?

**Comment by hi-subin** [comment]
1, 2, 3, 4가 더 깔끔할 것 같아서요 !

**Comment by 2480258** [comment]
변경했습니다(#16).
