### ISSUE TITLE
리뷰 조회 - 404 에러

### ISSUE THREAD

**Issue by hi-subin** [KHUGREEN/greenReview_backend#15]
/reviews/${ID}?page=${page}&size=${size}

여기 ID에 1번 입력하고 get 해봤는데 404 에러가 나요
1번 제품에 리뷰 입력하고 확인했는데, 에러가 나서 확인 한번 부탁드려요 ~

**Comment by 2480258** [comment]
/review/list/1?page=0&size=1로 할 때 정상동작 확인했습니다.
2주 전인가 바꿨었던 것 같은데 말씀을 안드렸네요....

```
[
    {
        "id": 545,
        "nickname": "이름",
        "content": "test",
        "checkTypes": [
            2
        ]
    }
]
```
