### ISSUE TITLE
상품 데이터 조회 - 통계 API 따로

### ISSUE THREAD

**Issue by hi-subin** [KHUGREEN/greenReview_backend#17]
상품 데이터 조회 API에서 checklists 부분만 따로 API 만들어 주실 수 있나요 ?

**Comment by hi-subin** [comment]
제 대답이나 확인이 필요할 때, Assignees 저한테 넘겨주시면 감사할 것 같아요 !
![image](https://user-images.githubusercontent.com/72721839/188937692-514d294e-f62c-42a7-9b8e-be641ed4c20b.png)

**Comment by 2480258** [comment]
추가했습니다(#19 ).
